package com.shop;

import java.util.ArrayList;
import java.util.Scanner;

public class View {
    private Operations op=new Operations();

    public void connectToDB(){
        boolean isConnect=op.connectToDB("billing","postgres","Maha@2021");
        if (isConnect){
            System.out.println("connection established.");
            options();

        }else System.out.println("failed to connect");
    }

    public void options(){

        Scanner in=new Scanner(System.in);

        int choice;

        do {
            System.out.println("Select any option");
            System.out.println("1.View top 10 purchases made by customers today\n2.View top 10 purchases made by customers this month" +
                    "\n3.View top 10 products sold this month based on quantity\n4.View unsold product this month" +
                    "\n5.View revenue generated by electronics category products this month\n6.View products sold more than 500 quantity this month" +
                    "\n7.View customers who purchased more than 50000 this month\n0.Exit");
            choice = in.nextInt();

            switch (choice){
                case 1->topPurchasesToday();
                case 2->topPurchasesThisMonth();
                case 3->topSoldProductsThisMonth();
                case 4->unsoldProductsThisMonth();
                case 5->revenueByElectronicsProductsThisMonth();
                case 6->soldProductsMoreThan500ThisMonth();
                case 7->purchasesMoreThan50000ThisMonth();

            }
        } while (choice!=0);
    }

    public void topPurchasesToday() {
        System.out.println("Fetching details...");
        ArrayList arr=op.topPurchaseToday();
        System.out.println("Fetch successfull...");

        if(arr.size()>0){
            System.out.printf("%15s %-15s %-20s %-20s %-16s%n", "Transaction ID", "Customer ID", "First name", "Last name", "Purchased Amount");
            for (Object object:arr){
                PurchaseToday obj=(PurchaseToday) object;
                System.out.printf("%-15d %-15d %-20s %-20s %-15.2f%n",
                        obj.getTransaction_id(),obj.getCustomer_id(),
                        obj.getFirst_name(),obj.getLast_name(),obj.getTotal_amount());
            }
        }


    }
    public void topPurchasesThisMonth() {
        System.out.println("Fetching details...");
        ArrayList arr=op.topPurchaseThisMonth();
        System.out.println("Fetch successfull...");

        if(arr.size()>0){
            System.out.printf("%-15s %-20s %-20s %-16s%n", "Customer ID", "First name", "Last name", "Purchased Amount");
            for (Object object:arr){
                TopCustPurchaseThisMonth obj=(TopCustPurchaseThisMonth) object;
                System.out.printf("%-15d %-20s %-20s %-15.2f%n",
                        obj.getCustomer_Id(), obj.getFirst_name(),obj.getLast_name(),obj.getTotal_amount());
            }
        }

    }
    public void topSoldProductsThisMonth() {
        System.out.println("Fetching details...");
        ArrayList arr=op.topSoldProductsThisMonth();
        System.out.println("Fetch successfull...");

        if(arr.size()>0){
            System.out.printf("%-15s %-40s %-20s%n", "Product ID", "name","Sold Quantity");
            for (Object object:arr){
                TopSoldProductsThisMonth obj=(TopSoldProductsThisMonth) object;
                System.out.printf("%-15d %-40s %-20d%n",
                        obj.getProduct_id(), obj.getName(),obj.getTotal_sold());
            }
        }

    }
    public void unsoldProductsThisMonth() {
        System.out.println("Fetching details...");
        ArrayList arr=op.unSoldProductsThisMonth();
        System.out.println("Fetch successfull...");

        if(arr.size()>0){
            System.out.printf("%-15s %-40s %-20s%n", "Product ID", "name","Category");
            for (Object object:arr){
                UnSoldProductsThisMonth obj=(UnSoldProductsThisMonth) object;
                System.out.printf("%-15d %-40s %-20s%n",
                        obj.getProduct_id(), obj.getName(),obj.getCategory());
            }
        }

    }
    public void revenueByElectronicsProductsThisMonth() {
        System.out.println("Fetching details...");
        ArrayList arr=op.revenueByElectronicsProductsThisMonth();
        System.out.println("Fetch successfull...");

        if(arr.size()>0){
            System.out.printf("%-15s %-40s %-15s %-20s%n", "Product ID", "name","quantity","Total Sold");
            for (Object object:arr){
                revenueByElectronicsProductsThisMonth obj=(revenueByElectronicsProductsThisMonth) object;
                System.out.printf("%-15d %-40s %-15d %-15.2f%n",
                        obj.getProduct_id(), obj.getName(),obj.getQuantity(),obj.getTotal_sold());
            }
        }


    }
    public void soldProductsMoreThan500ThisMonth() {
        System.out.println("Fetching details...");
        ArrayList arr=op.soldProductsMoreThan500ThisMonth();
        System.out.println("Fetch successfull...");

        if(arr.size()>0){
            System.out.printf("%-15s %-40s %-20s %-20s%n", "Product ID", "name","category","Sold Quantity");
            for (Object object:arr){
                TopSoldProductsThisMonthMoreThan500 obj=(TopSoldProductsThisMonthMoreThan500) object;
                System.out.printf("%-15d %-40s %-20s %-20d%n",
                        obj.getProduct_id(), obj.getName(),obj.getCategory(),obj.getSold_quantity());
            }
        }

    }
    public void purchasesMoreThan50000ThisMonth() {
        System.out.println("Fetching details...");
        ArrayList arr=op.purchasesMoreThan50000ThisMonth();
        System.out.println("Fetch successfull...");

        if(arr.size()>0){
            System.out.printf("%-15s %-20s %-20s %-20s%n", "Customer ID", "First name", "Last name","Purchased Amount");
            for (Object object:arr){
                TopCustPurchaseThisMonth obj=(TopCustPurchaseThisMonth) object;
                System.out.printf("%-15d %-20s %-20s %-20.2f%n",
                        obj.getCustomer_Id(), obj.getFirst_name(),obj.getLast_name(),obj.getTotal_amount());
            }
        }

    }
}
